apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: redis-master
        image: 503673903511.dkr.ecr.us-east-1.amazonaws.com/csye7374:latest
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: db.pass
        - name: REDIS-MASTER
          value: "true"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
          - name: redis
            containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
            memory: "32Mi"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
          - mountPath: /redis-master-data
            name: data
      - name: sentinel
        image: k8s.gcr.io/redis:v1
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - name: sentinel
            containerPort: 26379
      volumes:
        - name: data
          emptyDir: {}