apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: redis-slave
        image: docker.io/adikelkar4/csye7374:redisslave
        resources:
          limits:
            cpu: "0.1"
            memory: "32Mi"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: db.pass
        - name: GET_HOSTS_FROM
          value: dns
        ports:
          - containerPort: 6379
            name: slave
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: sentinel
        image: k8s.gcr.io/redis:v1
        env:
          - name: redis-sentinel
            value: "true"
        ports:
          - name: sentinel
            containerPort: 26379
      - name: redis-exporter
        image: oliver006/redis_exporter:v0.21.1
        resources:
          requests:
            cpu: "0.1"
            memory: 32Mi
        ports:
        - containerPort: 9121
          name: redis-metrics
      volumes:
        - name: data
          emptyDir: {}