apiVersion: v1
kind: Service
metadata:
  name: redis-monitor-svc
  labels:
    app: redis
    k8s-app: redis-monitor-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121" 
spec:
  ports:
  - port: 9121
    name: metrics
  selector:
    app: redis