apiVersion: v1               
kind: Pod                    
metadata:
  name: csye7374
  labels:                                                 
    app: csye7374
spec:
  containers:
  - name: csye7374
    image: 166427690327.dkr.ecr.us-east-1.amazonaws.com/csye7374:latest
    env:
    - name: GREETING
      value: "Warm greetings to"
    - name: HONORIFIC
      value: "The Most Honorable"
    - name: NAME
      value: "Kubernetes"  
    ports:
    - containerPort: 8080    
      protocol: TCP
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5 